abstract non-atomic RUD operations and implement handle deletion
caseydavenport/libcalico-go pull request #7
Opened 2019-02-05 23:20 UTC by briansan

2019-02-06 01:23 UTC, caseydavenport requested changes

2019-02-06 01:23 UTC, caseydavenport commented on lib/backend/model/atomic.go
> +type AtomicDelete interface {
I think something like `DeletionMarker` is probably a better name for this interface, since the primary thing objects which implement this do is be marked for deletion.

2019-02-06 01:23 UTC, caseydavenport commented on lib/backend/model/block.go
> +	AtomicDelete
I don't think it needs to have the interface defined inline - just needs the methods defined.

2019-02-06 01:23 UTC, caseydavenport commented on lib/backend/model/atomic.go
> +type AtomicDelete interface {
Then, the methods would be `MarkDeleted()` and `IsDeleted`

2019-02-06 01:23 UTC, caseydavenport commented on lib/backend/model/block_affinity.go
> +	AtomicDelete
Same here - don't think you need the interface inline within the struct.

2019-02-06 01:23 UTC, caseydavenport commented on lib/ipam/ipam_block_reader_writer.go
> +func (rw blockReaderWriter) atomicQuery(ctx context.Context, k model.Key, revision string) (*model.KVPair, error) {
I'm not a huge fan of the name `atomicQuery`. I think because we're not actually performing an atomic operation.

What about dropping the "atomic-ness" from the description altogether? 

e.g., the generic:
- queryObject
- deleteObject
- updateObject

2019-02-06 01:23 UTC, caseydavenport commented on lib/ipam/ipam_block_reader_writer.go
> +// updateAffinity ...
Need to populate these comments, or just drop them.

2019-02-06 01:23 UTC, caseydavenport commented on lib/ipam/ipam_block_reader_writer_test.go
> +	It("should delete a block on query if the original delete failed", func() {
Let's discuss testing for this tomorrow - I don't think this guy is testing the thing we want.

2019-02-06 01:29 UTC, briansan commented on lib/backend/model/block.go
> +	AtomicDelete
Don't you think it's good practice to explicitly declare that a struct implements an interface to get some free compile-time checks?

2019-02-06 16:57 UTC, caseydavenport commented on lib/backend/model/block.go
> +	AtomicDelete
I would! But, I wasn't aware that adding the interface to the struct gave you compile time checks.

According to some simply playing around, I don't actually see it failing at compile time: https://play.golang.org/p/P79-1c2E_nI

Maybe I'm missing something though?

2019-02-06 17:50 UTC, briansan commented on lib/backend/model/block.go
> +	AtomicDelete
eek barba duke, that's awkward...

2019-02-08 00:14 UTC, caseydavenport commented on lib/ipam/ipam_block_reader_writer_test.go
> +	It("should delete a block on query if the original delete failed", func() {
@briansan I think if you remove this test we can merge this PR and then work on the testing afterwards.

2019-02-08 03:30 UTC, briansan commented
@caseydavenport ready to merge?

2019-02-08 17:10 UTC, merged